[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [{ id = "check-yaml" }, { id = "end-of-file-fixer" }, { id = "trailing-whitespace" }]

[[repos]]
repo = "local"
hooks = [
  { id = "oxlint", name = "Oxlint (Linter)", entry = "frontend/node_modules/.bin/oxlint --deny-warnings", language = "system", files = "\\.(js|jsx|ts|tsx)$" },
  { id = "oxfmt", name = "Oxfmt (Formatter)", entry = "frontend/node_modules/.bin/oxfmt --no-error-on-unmatched-pattern", language = "system", files = "\\.(js|jsx|ts|tsx|json|jsonc|yaml|yml|md)$" },
]
